### ISSUE TITLE
Variable reference typo in patch file

### ISSUE THREAD

**Issue by barmazu** [solsticedhiver/archiso-sb-shim#2]
Hi!
I latest patch version there's a typo in variable reference:
https://github.com/solsticedhiver/archiso-sb-shim/blob/16aac5c59f72144aa371e9779885ffe0323e070f/mkarchiso.patch#L187

With this typo and patch in-place creation of the ISO file will fail.
Thank you for your hard work.

**Comment by solsticedhiver** [comment]
hi.

I don't see it. Which typo?

**Comment by barmazu** [comment]
Hi,
`$"{isofs_dir}/EFI/BOOT/DB.cer"` should be `"${isofs_dir}/EFI/BOOT/DB.cer"`
The latter will evaluate properly, while the former will be literal `{isofs_dir}`
Thanks.
